# Generated by Django 4.2.9 on 2024-02-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_alter_function_args'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='executed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='command',
            name='args',
            field=models.JSONField(null=True),
        ),
    ]
