# Generated by Django 4.2.9 on 2024-02-08 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_alter_command_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='asyncro',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ScheduledCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=20)),
                ('interval_number', models.IntegerField(default=1)),
                ('interval', models.CharField(max_length=20)),
                ('at', models.CharField(max_length=5, null=True)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.command')),
            ],
        ),
    ]
