# Generated by Django 4.2.9 on 2024-02-15 03:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0007_scheduledcommand_run_once_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledcommand',
            name='command',
        ),
        migrations.AddField(
            model_name='command',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controller.scheduledcommand'),
        ),
        migrations.AddField(
            model_name='scheduledcommand',
            name='args',
            field=models.JSONField(null=django.db.models.deletion.CASCADE),
            preserve_default=django.db.models.deletion.CASCADE,
        ),
        migrations.AddField(
            model_name='scheduledcommand',
            name='asyncro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduledcommand',
            name='function',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controller.function'),
        ),
        migrations.AlterField(
            model_name='scheduledcommand',
            name='job_id',
            field=models.CharField(default=uuid.UUID('c806f19c-1631-4781-8067-4636b2ce68a5'), max_length=20),
        ),
    ]
