# Generated by Django 4.2.9 on 2024-02-15 03:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0008_remove_scheduledcommand_command_command_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledcommand',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.function'),
        ),
        migrations.AlterField(
            model_name='scheduledcommand',
            name='job_id',
            field=models.CharField(default=uuid.UUID('30743ed9-ada8-4347-b30b-be61b49b6dc1'), max_length=20),
        ),
    ]
